apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitserver
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: sourcegraph/alpine:3.12@sha256:ce099fbcd3cf70b338fc4cb2a4e1fa9ae847de21afdb0a849a393b87d94fb174
          command: ["sh", "-c", "if [[ \"$(stat -c '%u' /data/repos)\" -ne 100 ]]; then chown -R 100:101 /data/repos; fi"]
          volumeMounts:
            - mountPath: /data/repos
              name: repos
          securityContext:
            runAsUser: 0
